### ISSUE TITLE
Change the payment instrument to stripe

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/commitcivi#3]
So to make it easier to distinguish between paypal and stripe, instead of using the same payment instrument "Credit Card" (1) for both, we will use 2 "Stripe/debit card" for stripe, and rename 1 to Paypal

we need to run regularly sql/fix_payment_type_stripe.sql

    update civicrm_contribution set payment_instrument_id=2 where payment_instrument_id=1 and trxn_id like "ch_%";

@rthouvenin, what's the best place to add that cron (hourly is fine)?

**Comment by rthouvenin** [comment]
Why not storing directly the correct payment instrument?
